### ISSUE TITLE
Touchpad support

### ISSUE THREAD

**Issue by st4ycool** [ekiefl/pooltool#101]
It seems that Pooltool doesn't work with touchpad

**Comment by ekiefl** [comment]
Can you describe the behavior you're observing? Pooltool works at the level of mouse position, and does not care what hardware was used to move the mouse.

**Comment by st4ycool** [comment]
So, simulator doesn't react on any touchpad events. No matter, is it aim mode or no, it doesn't even move screen with 'V' key. 

upd:
After few minutes I tried with trackback with trackball ( red dot in the middle of keyboard of ThinkPad), and it works as intended. 
I am on Ubuntu 22.04.3

p.s. do you have any plans on sounds?

P.s.p.s. big respect for this truly amazing work!

**Comment by ekiefl** [comment]
That is unfortunate :\

I'm not sure how I can help with that. If the touchpad controls the mouse, it should control the game, with a few caveats.

First, since you're on Linux, make sure you run

```bash
pip uninstall panda3d -y
pip install --pre --extra-index-url https://archive.panda3d.org/ panda3d
```

If you can only move just a little in any direction before the cursor goes out of the game screen, you need to run the above step.

Second, any unlikely scenario can occur where the game window is active, and the mouse position is frozen, but lies outside the game window. When this happens, no mouse movement controls control the game. However, this is independent of the mouse hardware. If you try the trackball and the trackpad right after one another, does the trackball work and the trackpad doesn't?

> p.s. do you have any plans on sounds?

Yes! Let me know if you want to collaborate on that.

> P.s.p.s. big respect for this truly amazing work!

Thank you very much.

p.s. How did you hear about pooltool?

**Comment by st4ycool** [comment]
hmm 
`Installing collected packages: panda3d
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pooltool-billiards 0.2.1 requires panda3d==1.10.13, but you have panda3d 1.11.0.dev3306 which is incompatible.
`

No, trackpad doesn't work after I play with trackball

How can I collaborate on introducing sounds into this beautiful simlator?

p.s. I asked stupid gpt what billiard games are available in the world and surprise surprise - pooltool was the first one in the list

**Comment by ekiefl** [comment]
> Installing collected packages: panda3d ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. pooltool-billiards 0.2.1 requires panda3d==1.10.13, but you have panda3d 1.11.0.dev3306 which is incompatible. 

This is an expected warning, since we are overriding pooltool's panda3d requirement. In the pooltool python env, can you run

```bash
python
```

Then:

```python
print(__import__("panda3d").__version__)
```

To exit,

```python
exit()
```

What version is printed out? It should be >1.10.13

You should give it another go and see if your experience feels better.

> p.s. I asked stupid gpt what billiard games are available in the world and surprise surprise - pooltool was the first one in the list

Wow, that's cool GPT has pooltool on the radar.

**Comment by ekiefl** [comment]
> How can I collaborate on introducing sounds into this beautiful simlator?

Are you a sound engineer, or do you have a good mic and access to a pool table? We basically need a collection of sound bytes that get mapped to different events, like ball-ball, stick-ball, and ball-cushion collisions. Some background "bar ambience" would also be good.

**Comment by st4ycool** [comment]
No, unfortunately I am no sound engineer.... neither I have the pool table. But maybe for first iteration just sounds from legendary pool games from internet would be enough? Like with your first table that had no 3d )

p.s. But I would be happy to help with coding... maybe!!! If you have some small tasks

**Comment by ekiefl** [comment]
I'm going to close this issue since there is no clear action to take.

Since pooltool installation instructions and build dependencies have been updated since this issue, it's possible this no longer an issue.

Feel free to reopen if this issue is still experienced using the current installation instructions
