### ISSUE TITLE
error re-installing panda3d

### ISSUE THREAD

**Issue by Hoodie2389** [ekiefl/pooltool#104]
Hi - 

There is an error when installing  the archive one and as a result I am not able to run_pooltool.bat - I am on windows - can you advise please? thanks

>> pip install --pre --extra-index-url https://archive.panda3d.org/ panda3d
Found existing installation: Panda3D 1.10.13
Uninstalling Panda3D-1.10.13:
  Successfully uninstalled Panda3D-1.10.13
WARNING: Ignoring invalid distribution -ip (c:\python39\lib\site-packages)
Looking in indexes: https://pypi.org/simple, https://archive.panda3d.org/
Collecting panda3d
  Downloading https://buildbot.panda3d.org/downloads/78f8e1eaa95071ae21c2f6d8f16768c7330c5f15/panda3d-1.11.0.dev3306-cp39-cp39-win_amd64.whl (61.2 MB)
     ---------------------------------------- 61.2/61.2 MB 10.1 MB/s eta 0:00:00
WARNING: Ignoring invalid distribution -ip (c:\python39\lib\site-packages)
Installing collected packages: panda3d
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pooltool-billiards 0.2.1 requires panda3d==1.10.13, but you have panda3d 1.11.0.dev3306 which is incompatible.
Successfully installed panda3d-1.11.0.dev3306

**Comment by ekiefl** [comment]
This is really more of a warning than an error. pip is just warning us that we're overriding the dependency resolver.

For this reason, I suspect your issue may be unrelated to this warning. I don't have much experience with bat files so I may have misconfigured it.

Can you describe what happens when trying the following things?

1. Executing run_pooltool.bat?
1. `python run_pooltool`?
1. `python sandbox/break.py`

Hopefully the second and third run without a problem.

**Comment by ekiefl** [comment]
I just realized my instructions assume you followed the developer installation instructions. If you installed via pip, you won't be able to run the second and third without a copy of the codebase.

Regardless, it would be useful to see the error you get when running the bat file.

**Comment by ekiefl** [comment]
@Hoodie2389 Without seeing the error you get when running the bat file, there is not much to go off. As I said, pip installing the latest panda3d version is not truly an error, and is almost certainly not the reason why you encountered a runtime error when running the bat file.

Since you've left me with no actions to take, I'm closing this. Please feel free to reopen if you can provide an error message.
