### ISSUE TITLE
xml error when save new table

### ISSUE THREAD

**Issue by chardian** [ekiefl/pooltool#38]
when I create a new table , the error occured:

pooltool\pooltool\ani\menu.py", line 1019, in func_save_table for dropdown in self.xml.root.findall(".//*[@name='new_table']/dropdown"): AttributeError: 'XMLMenu' object has no attribute 'root'. Did you mean: 'roots'?

**Comment by chardian** [comment]
There is no button to start, and when I create a new table , the error occured:


`pooltool\pooltool\ani\menu.py", line 1019, in func_save_table
    for dropdown in self.xml.root.findall(".//*[@name='new_table']/dropdown"):
AttributeError: 'XMLMenu' object has no attribute 'root'. Did you mean: 'roots'?`

**Comment by ekiefl** [comment]
Hey @chardian I'm sorry about this. The menu you're seeing is a work in progress, and should have been developed in a separate branch. I've made a couple of changes and pushed things into a working state.

After a `git pull`, start up the game and from the menu press 'n'. It should start you in a new game (although making your own table is still not working due to the menu). Let me know if that fixed it, or if you have other errors.

**Comment by chardian** [comment]
Press 'N" not work
the error still exists



line 987, in get_menu_options
    'table_type': self.xml.root.find(".//*[@name='table_type']").attrib['selection']
AttributeError: 'XMLMenu' object has no attribute 'root'. Did you mean: 'roots'?

**Comment by chardian** [comment]
after git reset --hard 950d8577108acf40f048a5990b4be5a0fd726a50

it's work fine,
thank you.

**Comment by ekiefl** [comment]
Yep sorry about that, I thought I had pushed the change but hadn't.

**Comment by ekiefl** [comment]
Can you please give it another try?

**Comment by chardian** [comment]
great job
