### ISSUE TITLE
Can not install panda3d 1.10.10

### ISSUE THREAD

**Issue by 123omari123** [ekiefl/pooltool#44]
Hi
When I started installing pooltool , python does not find panda3d 1.10.10 package, also I could not find required package anywhere to install. So, I can not install pooltool on windows 10, python 3.11

**Comment by ekiefl** [comment]
I think I am right in saying that panda3d 1.10.10 does not support python 3.11, since it _just_ came out.

Either way, I'm sorry to say that the game is pretty much unusable on windows until panda3d 1.11 is released.

The API should work though. If that's what you want, you should follow the developer instructions in the README.md, which uses python 3.8.10.

Sorry I'm not able to help you out more.

**Comment by 123omari123** [comment]
Ok, I just wanted billiard simulator which is based on real physics and I
thought pooltool  was most appropriate one. Thanks anyway.

**Comment by ekiefl** [comment]
Thanks for checking out the project.
