### ISSUE TITLE
ImportError when trying to load the app (M1 mac)

### ISSUE THREAD

**Issue by edoson** [ekiefl/pooltool#47]
Hi, 

I'm on MacOS with apple M1 chip.  Installation went smooth, but when trying to run (`python run_pooltool`) I get the following error:

```
Traceback (most recent call last):
  File "run_pooltool", line 6, in <module>
    from pooltool.ani.animate import Play
  File "/Users/idodavid/dev/pooltool/pooltool/__init__.py", line 8, in <module>
    import pooltool.ani.utils as autils
  File "/Users/idodavid/dev/pooltool/pooltool/ani/utils.py", line 7, in <module>
    from pandac.PandaModules import NodePath, PGItem, Vec4
  File "/Users/idodavid/miniforge3/envs/pooltool/lib/python3.8/site-packages/pandac/PandaModules.py", line 28, in <module>
    from panda3d.vision import *
ImportError: dlopen(/Users/idodavid/miniforge3/envs/pooltool/lib/python3.8/site-packages/panda3d/vision.cpython-38-darwin.so, 0x0002): Library not loaded: lib/libopencv_imgproc.2.4.dylib
```

Some binaries are probably missing, or a path should be set? 

Will appreciate any help, 
Ido

**Comment by ekiefl** [comment]
Hey @edoson thanks for checking out the project. If I may ask, how did you find out about pooltool? I'm curious because this repo has received a lot more attention in the last week than it has in recent months. Were you referred by a link?

Anyways, thanks for this error report. I am able to reproduce this error on an M1 mac.

The error comes from the internals of pooltool's primary dependency, panda3d. I've filed an error report on their repo, and you can track any progress there: https://github.com/panda3d/panda3d/issues/1393. It seems like they are targeting a fix that would be included in the 1.10.13 release.

I'll keep this issue open to improve its visibility until 1.10.13 is released.

**Comment by edoson** [comment]
Hi Evan, Thanks for your quick reply and for opening an error report. I've reached your project by directly googling for an open source pool simulator. I'm a deep learning researcher and want to tackle the problem of predicting pool balls trajectory using AI, essentially learning the real world physics or in that case, the physics you've so nicely implemented in the simulator.

**Comment by edoson** [comment]
@ekiefl Thanks for the support, indeed switching all imports of kind `pandac.PandaModules` to `panda3d.core` fixed the issue, the application is now running.

**Comment by ekiefl** [comment]
Very interesting.

I had always created this project with the intent of creating a DL model that would, given a table configuration, spit out the cue stick parameters (a, b, phi, theta, V0) that would result in a "good" shot.

If you're interested in working together, please shoot me an email, which you can find on my website: [ekiefl.github.io](https://ekiefl.github.io/). Perhaps we could collaborate, though my time is rather limited. I assume yours is too.

**Comment by ekiefl** [comment]
> @ekiefl Thanks for the support, indeed switching all imports of kind pandac.PandaModules to panda3d.core fixed the issue, the application is now running.

Great. I will add those changes to the main branch. You should probably pull those changes once I add them, rather than have your repo start diverging too much. I am actively working on the codebase, which is far from polished.

Although it isn't documented, press n in the menu to start playing (yeah, that's where we're at development wise lol)
